project_id = "pkvayugxzgkoipclcpli"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
image_transformation = { enabled = true }

[auth]
enabled = true

[edge_runtime]
enabled = true

[functions.create-mollie-payment]
verify_jwt = false

[functions.mailchimp-newsletter]
verify_jwt = false

[functions.create-shop-order]
verify_jwt = false

[functions.create-partner-payment]
verify_jwt = false

[functions.mollie-webhook]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.handle-auth-webhook]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false